name: run my vanilla Cypress tests
on: 
  schedule:
      - cron: "0 * * * *"
      
  workflow_dispatch:

jobs:
  checkout-and-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: run cypress tests with chrome
        uses: cypress-io/github-action@v2
        timeout-minutes: 240
        with:
          browser: chrome
          config-file: cypress.config.js
